# Generated by Django 4.1.13 on 2024-10-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=500)),
                ('data_inicio', models.CharField(max_length=500)),
                ('data_fim', models.CharField(max_length=500)),
                ('valor', models.CharField(max_length=500)),
                ('local', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('link_compra', models.URLField(default='')),
                ('link_validacao', models.URLField(default='')),
                ('url_imagem', models.URLField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
