# Generated by Django 5.1.2 on 2024-10-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('local', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('link_compra', models.URLField()),
                ('link_validacao', models.URLField()),
            ],
        ),
    ]
