# Generated by Django 4.1.13 on 2024-10-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='link_compra',
        ),
        migrations.AlterField(
            model_name='evento',
            name='link_validacao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='url_imagem',
            field=models.TextField(),
        ),
    ]
